#import "../funkcije.typ": dodatak, todo

= Spisak korišćenih pojmova <dodatak-2>

#dodatak(
  table(
    [*Pojam*],
    [*Objašnjenje*],
    [Blok],
    [Najmanja jedinica interakcije sa datotekom i diskom.],
    [Stranica],
    [Sirovi bajtovi jednog bloka učitani u radnu memoriju.],
    [Bafer],
    [Omotač oko stranice u memoriji koji sadrži dodatne metapodatke za upravljanje stanjem.],
    [Pinovanje],
    [Označavanje bafera od strane transakcije kako se on ne bi izbacio iz radne memorije dokle god je u upotrebi.],
    [Log sekvenca],
    [Unikatni identifikator zapisanog _log_-a na osnovu koga se održava redosled operacija.],
    [Mirna kontrolna tačka],
    [Oznaka u _log_ datoteci nakon koje sistem za oporavak ne mora da gleda u prošlost jer nema aktivnih transakcija],
    [_Deljeni_ katanac],
    [Mehanizam zaključavanja bloka koji omogućava višenitno čitanje istih podataka bez modifikacija.],
    [_Ekskluzivni_ katanac],
    [Mehanizam zaključavanja bloka koji garantuje isključivi pristup podacima zarad modifikacije.],
    [Prljavo čitanje],
    [Problem konkurentnosti gde jedna transakcija čita nepotvrđene izmene druge transakcije.],
    [Fantomsko čitanje],
    [Problem konkurentnosti gde se tokom obrade opsega pojave novi slogovi umetnuti od strane druge transakcije.],
    [Slog],
    [Najmanja instanca podataka koja opisuje jedan red iz tabele.],
    [Šema],
    [Definicija atributa, tipova, dužina i ograničenja kolona za jednu tabelu.],
    [Kataloška tabela],
    [Sistemska tabela baze u kojoj se perzistiraju metapodaci potrebni za funkcionisanje sistema.],
    [_HyperLogLog_],
    [Probabilistička struktura podataka iskorišćena za procenu broja jedinstvenih vrednosti.],
    [Virtuelna tabela],
    [Skup rezultujućih slogova nakon primene relacionih operatora koji nisu nužno perzistirani na disku.],
    [Izraz],
    [Aritmetička kombinacija konstanti, operatora i kolona čijom evaluacijom nad nekim slogom dobijamo konstantnu numeričku vrednost.],
    [Član],
    [Objekat koji poredi dva izraza na osnovu nekog operatora poređenja. Evaluacijom dobijamo da li je rezultat poređenja istinit ili ne.],
    [Predikat],
    [Logička kombinacija članova i čijom evaluacijom dobijamo konstantnu logičku vrednost.],
    [Protočna obrada],
    [Izvršavanje stabla operatora obradom slogova jedan po jedan, bez čuvanja međurezultata u memoriji.],
    [Materijalizovana obrada],
    [Čuvanje svih (ili delimičnih) izračunatih međurezultata na disku ili u memoriji, potrebno za operacije sortiranja i agregacije.],
    [Redukcioni faktor],
    [Statistički broj koji označava za koliko će se puta smanjiti količina izlaznih slogova pod dejstvom određenog predikata.],
    [Iskaz],
    [Najviša sintaktička kategorija koja opisuje potpunu _SQL_ operaciju i sadrži sve neophodne podatke da bi se ista izvršila (eng. _Statement_).],
    [_Pratt parsing_],
    [Tehnika _recursive descent_ parsiranja za efikasnu validaciju izraza i obradu aritmetičkih prioriteta.],
    [_Generics_],
    [Mehanizam _Java_ programskog jezika za pisanje agnostičnog koda kojeg različiti tipovi koriste na isti način],
    [Punokvalifikujuće ime],
    [Ime kolone sastavljeno od imena tabele i same kolone kako bi se izbegla dvosmislenost.],
    [Parcijalni evaluator],
    [Komponenta koja statički svodi izraze sa trivijalnim operacijama na konstante već u trenucima kreiranja plana upita.],
    [Protokol serijalizacije],
    [Skup pravila konvertovanja struktura podataka u linearan niz bajtova za prenos kroz mrežu.],
    [Ugrađeni režim],
    [Režim rada baze podataka gde ona postoji u okviru istog operativnog procesa kao i klijentska aplikacija koja je koristi.],
    [Serverski režim],
    [Režim rada gde se baza podataka ponaša kao server, primajući naredbe sa mreže od više nezavisnih klijenata.],
    [_Socket_],
    [Par _IP_ adrese i porta koji, uz dodatnu logiku, omogućava komunikaciju preko mreže],
    [Zavisnost],
    [Softverska biblioteka od koje zavisi izgradnja i uspešan rad sistema.],
    [_Native_ instrukcije],
    [Instrukcije specifičnog operativnog sistema],
  ),
)
