#import "../funkcije.typ": dodatak, todo

= Spisak korišćenih skraćenica <dodatak-1>

#dodatak(
  table(
    table.header[*Skraćenica*][*Značenje*],

    [SUBP],
    [Sistem za upravljanje bazama podataka],
    [_SQL_],
    [_Structured Query Language_],
    [_AST_],
    [_Abstract Syntax Tree_],
    [_ACID_],
    [_Atomicity, Consistency, Isolation, Durability_],
    [_MVCC_],
    [_Multi Version Concurrency Control_],
    [_FIFO_],
    [_First In First Out_],
    [_LRU_],
    [_Least Recently Used_],
    [_LRM_],
    [_Least Recently Modified_],
    [_RAII_],
    [_Resource Acquisition Is Initialization_],
    [_RBO_],
    [_Rule-Based Optimisation_],
    [_HBO_],
    [_Heuristics-Based Optimisation_],
    [_CBO_],
    [_Cost-Based Optimisation_],
    [_JDBC_],
    [_Java Database Connectivity_],
    [_SPA_],
    [_Slotted Page Architecture_],
    [_RSS_],
    [_Relational Storage System_],
    [_CI_],
    [_Continuous Integration_],
    [_CD_],
    [_Continuous Delivery_],
    [U/I],
    [Ulaz/Izlaz],
    [_API_],
    [_Application Programming Interface_],
    [_EOF_],
    [_End Of File_],
    [_UTF-8_],
    [_Unicode Transformation Format_],
    [_RESP_],
    [_REdis Serialization Protocol_],
  ),
)
